tutorialsIndex_en = {"Getting Started", "Basics", "Map and Spawns", "Professions", "Addons and mounts", "Advanced", "Rules", "FAQ"}

tutorialsInfo_en = {
    {
        {name = "01. Introduction", text = "Nutopia is a low rate 5x custom RPG server. We have been working on for a total of 3 years now, the map has been in development on and off for about 9 years. \n\nThe server has been online in AUS for 3 years but is now making the movie to the US.", img = "imgs/basic/intro"}, 
        {name = "02. Getting Started", text = "Before you start, we recommend you to read information about 'Basics': \n\n- Tasks. \n- Autoloot. \n- Outposts. \n- Elite Montsers.\n- Starter Spawns.", img = "imgs/basic/b1"}, 
        {name = "03. Server information", text = "Some basic info: \n\n- EXP rate - 5\n- Loot rate - 2\n- Skill rate - 6\n- Magic Rate - 5\n- Autoloot enabled. \n- Custom Client.", img = "imgs/basic/info"}, 
        {name = "04. Discord", text = "Our discord is: discord.gg/nRfzhkT \n\nJoin our Discord server for latest updates, client and news. There you can also report bugs, make suggestions, show off your items or just chat amongst the community.", img = "imgs/basic/discord"}, 
        {name = "05. Nutopia Wiki", text = "For more information check Nutopia wiki: nutopia.fandom.com/wiki.\n\nIt is a collaborative community website about Nutopia that anyone, including you, can build and expand. Wikis like this one depend on readers getting involved and adding content.", img = "imgs/basic/wiki"}, 
        },
    {
        {name = "01. Autoloot", text = "The auto loot system is exactly what it sounds like, though even more automatic than RL Tibia. It will pick up any individual item that you have set or any item that belongs to preset groups of items if you have them activated. \n\nTo use the auto loot system, use the command:\n!autoloot {add,remove,show,clear}, itemOrGroupName\n\nThis may look a little confusing but a few examples should clear it up. If you want to automatically loot gold coins simply say: !autoloot add, gold coin\nNOTE: don't add any plurals just use the individual item name as its spelt when you 'look' at it.\n\nNow any monster that you kill will be checked for gold coins and if they have dropped them, they will be moved to your backpack. If you have too much money and are sick of converting gold coins to platinum then you may want to stop auto looting them, to do that use the command like this:\n!autoloot remove, gold coin\n\nNOTE: same rules here as adding the item If you want to see a list of all the items you have set to auto loot, say:\n!autoloot show\n\nNOTE: no parameter needed for this command If you are sick of auto loot all together or want to start your list fresh, say:\n!autoloot remove\n\nNOTE: no parameter needed for this command", img = "imgs/basic/autoloot"},
        {name = "02. Autoloot Groups", text = "Adding lots of similar items, such as creature products and gems, can be tedious so there are predefined lists you can use instead:\n\n- infused\n- balanced\n- sharpened\n- weithed\n- precise\n- reinforced\n- gems\n- creature products\n- uncommon\n- rare\n- epic\n- legendary\n- artifact\n\nBonus: energetic backpack\n\nTo use any of the these just use the add command and replace the item name with one of the group names. The trait group names will pick up any creature product associated with Smithing or Alchemy. The Enchanting level lists will pick up any items a monster drops that are enchanted at that level.", img = "imgs/basic/autolootgroups"},
        {name = "03. Tasks", text = "Tasks are small quests that require you to kill a certain number of a creature for cash, experience and Enchant gem rewards. You can start tasks at NPC Adonia in the Varbosa depot. You can have up to 20 different tasks going at the same time but once you hand a task in you cannot repeat it for another 3 days. Parties can complete tasks together as long as all players in the party are within shared experience range (level and distance).\n\nFor a list of available creatures talk to NPC Adonia and ask for a list.\n\nTasks kill count and rewards are tiered based on the task monsters health. The more health the monster has the more you will have to kill but the experience and cash rewards scale accordingly, also the gem type gets better according to the following table:\n\n- 0-1000hp (50k kills) = Uncommon gems\n- 1000-3000hp (100 kills) = Rare gems\n- 3000-500hp (135 kills) = Rare Gems\n- 5000-7000hp (175 kills) = Epic Gems\n- 7000-10000hp (225 kills) = Epic Gems\n- Over 10000hp (300 kills) = Legendary Gems.\n\n For more information visit Nutopia wikipedia or ask Npc Adonia about the 'list'.", img = "imgs/basic/tasks"},
        {name = "04. Elite Monsters", text = "Every time you kill something that isn’t a player there is a chance it will spawn an elite version of itself. The elite monster will spawn on the original monsters corpse and you can tell it is an elite by the black skull next to its name. It will have double the HP of the original monster and hit double in every attack. Elite monsters drop the same loot as the original plus, if your level is in the right range, an energetic backpack containing valuable items and crystal coins. Monsters with more HP are classed in higher elite monster tiers and have better loot.\n\n- Tier1: 0-3000hp: 0.3% Chance to Spawn\n- Tier2: 3001-9000hp: 0.3% Chance to Spawn\n- Tier3: 9001-15000hp: 0.3% Chance to Spawn\n- Tier4: 15001-40000hp: 0.3% Chance to Spawn\n- Tier5: Over 40001hp: 0.5% Chance to Spawn\n\nFor an elite monster to drop an energetic backpack with extra valuables you need to be in the level range of the monster. If the killers level is between 0 and 99 then the base monster needs to give 150 exp or more. If the killers level is 100+ then the monster needs to give at least Level * 5 exp. For example:\n\nIf the killers level is 150, the base monster would need to give at least 750 exp for an energetic backpack to drop.", img = "imgs/basic/elites"},
        {name = "05. Outposts", text = "Outposts are little strongholds in the wilderness surrounding Varbosa. They each have a teleport pad and a few supply NPCs.\n\nThere is currently 6 Outposts in the world.\n\nAt the moment they just serve as a way to get around the map quicker but in the future they will have more functions.", img = "imgs/basic/outposts"},
        {name = "06. Quests", text = "Around the world, there are normal quests with puzzles and chest rewards. Below are some examples, but there are more hidden quests for you to explore.\n\n- MMS Quest\n- Black Knight Quest\n- Falcon Quest\n- Annihilator Quest\n- Arc Quest\n\nOn the server their are unique and custom quests. We have a fully scripted boss enounter at the end of the servers main quest chain. It has proper boss mechanics that require coordination to complete.  ", img = "imgs/basic/quests"},
         },	
    {
        {name = "01. Nutopia Map", text = "Actual Nutopia minimap. If you want to see the full map, visit our Discord!", img = "imgs/map/m1"},
        {name = "02. Varbosa", text = "Varbosa is the main city in Nutopia. It is the only city, though there are Outposts where you can resupply and activate Waypoints.\n\nDon't forget to activate the Home Waypoint just north of the depot!\n\n1. Bank\n2. Adonai (Tasks)\n3. Zurga (Rares)\n4. Gorn (Backpacks and misc)\n5. Romella (Weapons)\n6. Sharon (Gem exchange)\n7. Yasir (Creature Products)\n8. Elane (Paladin Shop)\n9. Soya (Loot)\n10. Xodet (Magic Shop)\n11. Promotion (Southeast of depot, upstairs)\n12. North Gate\n13. East Gate\n14. Alchemy\n15. Smithing\n16. Plots ", img = "imgs/map/m2"},
        {name = "03. Starter Spawns", text = "1. Trolls\n2. Wild warriors\n3. Cyclops\n4. Elfs\n5. Minotaurs\n6. Orcs\n7. Tarantulas\n8. Larvas\n9. Tombs\n10. Ancient Scarabs\n11. Dragons\n12. Giant Spiders", img = "imgs/map/m3"},
    },	
    {
        {name = "01. Mining", text = "Mining is the skill used to collect ores from special metal veins. You can view your current mining skill by using the command !crafting\n\nWhen you come across a metal vein on the map, depending on your mining skill, you can use your pick on it to mine it. Each time you do will give you a tick to your next mining level and a chance to collect an or or enchant gem of the particular vein mined or destroy it.\n\nAs your mining skill increases you will be able to mine even stronger metal veins.\n\nOres gained from mining are used in Smithing to enhance existing items with different stats.\n\nTier1: Basalt [Minimum level: 10 Respawn time: 27-33 min]\nTier2: Nicolite [Minimum level: 15 Respawn time: 40-50 min]\nTier3: Altarus [Minimum level: 20 Respawn time: 56-66 min]\nTier4: Aredite [Minimum level: 40 Respawn time: 67-83 min]\nTier5: Tartarite [Minimum level: 60 Respawn time: 162-198 min]\nTier6: Iridium [Minimum level: 80 Respawn time: 324-396 min]", img = "imgs/profesion/p1"},
        {name = "02. Smithing", text = "Smithing is the skill used to enhance existing items with different stats. You can view your current farming skill by using the command !crafting\n\nTier1: Basalt [Smelting level:10 Smithing level:15]\nTier2: Nicolite [Smelting level:15 Smithing level:20]\nTier3: Altarus [Smelting level:25 Smithing level:30]\nTier4: Aredite [Smelting level:35 Smithing level:40]\nTier5: Tartarite [Smelting level:45 Smithing level:50]\nTier6: Iridium [Smelting level:55 Smithing level:60]", img = "imgs/profesion/p2"},
         {name = "- Introduction", text = "Unlike Enchanting, with smithing you can choose which stat you want to boost, though it can only be a single stat and is flat point increase rather than a percentage increase.", img = "imgs/profesion/p3"},
         {name = "- Smelting", text = "To start smithing head to the smithy building east of the depot. You will need at least 5 ores gained from Mining and and at least 5 coal pieces, which can be bought from NPC Byron. \n\nUsing the 5 coal pieces on a furnace will bring it up to heat for 75 seconds which will allow you to use the 5 ores on the furnace and convert it into its metal bar.", img = "imgs/profesion/p4"},
         {name = "- Smithing", text = "Once you have enough metal bars you can start upgrading your equipment. Place the piece you want to upgrade on the alter next to the anvil and “use” the anvil. A prompt will appear asking which bar you want to use depending on what bars you have enough of in your inventory.", img = "imgs/profesion/p5"},
         {name = "- Tiers", text = "After selection which bar you want to use you will be asked how many of them you want to use. Using more bars will give a higher tier in that metals smithed skill and therefore more skill points. Each tier needs a further 10 bars.", img = "imgs/profesion/p6"},
         {name = "- Traits", text = "Next you will be asked what trait item you want to use. The items that you have enough of in your inventory will be named and followed by what trait they will give. This determines what skill will be used on the item. A full list of items used for each trait is below.", img = "imgs/profesion/p7"},
         {name = "- Flux", text = "After choosing what trait item you will use, if you have any flux associated with the metal you originally picked you will be asked if you want to use it. Flux’s can be purchased from NPC Byron. Smithing starts with a 50% chance of success and can be increased by using different amounts of flux and by increasing your smithing skill. On failure the smithing ingredients are lost but the equipment remains unchanged.\n\nA final prompt will ask you to confirm you want to use all the materials you selected and tell you your chance of success. If you select ‘yes’ then the materials will be lost and, if successful, your item will give the new stats you smithed.", img = "imgs/profesion/p8"},
         {name = "- Items required", text = "- Infused (magic level): 3x Elvish Talisman / 5x Dragon's Tail / 15x Spider Silks / 20x Ogre Ear Studs / 40x Golden Lotus Broochs / 60x Book Pages.\n\n- Sharpened (sword skill): 3x Orc teeths / 5x Cave Turnips / 15x Blue Crystal Splinters / 20x Hellhound Slobbers / 40x Orbs / 60x Vexclaw Talons.\n\n- Balanced (axe skill): 3x Skull Belts / 5x Cultish Robes / 15x Brown Crystal Splinters / 20x Blazing Bones / 40x Hellflayer Horns / 60x Inkwells.\n\n- Weighted (club skill): 3x Orc Leathers / 5x Cyclops toes / 15x Red Crystal Fragments / 20x Demonic Essences / 40x Soul Orbs / 60x Piece of Dead Brains.\n\n- Precise (distance skill): 3x Minotaur Leathers / 5x Hellspawn Tails / 15x Hydra Heads / 20x Frazzle Tongues / 40x Peacock Feather Fans / 60x Silken Bookmarks.\n\n- Reinforced (shielding skill): 3x Green Dragon Leathers / 5x Green Dragon Scales / 15x Red Dragon Leathers / 20x Red Dragon Scales / 40x Frazzle Skins / 60x Fiery Hearts.", img = "imgs/profesion/p10"},
        {name = "03. Farming", text = "Farming is the skill used to harvest fruit and seeds off special plants. You can view your current farming skill by using the command !crafting\n\nWhen you come across a special plant on the map, depending on your farming skill, you can use a scythe or sickle on it to harvest it. Each time you do will give you a tick to your next farming level and a chance to collect a fruit or seed of the particular plant harvested or destroy it.\n\nAs your farming skill increases you will be able to harvest even stronger plants.\n\nFruits gained from farming are used in Alchemy to create potions that increase your stats.\n\nSeeds gained from farming are used on your own private Plots to grow plants only you can harvest.\n\nTier 1: Cloud Bell (Farming level: 10 Time to respawn: 30min)\nTier 2: Banora (Farming level: 15 Time to respawn: 45min)\nTier 3: Nightlock (Farming level: 20 Time to respawn: 60min)\nTier 4: Niphredil (Farming level: 40 Time to respawn: 75min)\nTier 5: Groomsblood (Farming level: 60 Time to respawn: 180min)\nTier 6: Thorian (Farming level: 80 Time to respawn: 360min)", img = "imgs/profesion/f1"},
         {name = "- Plots", text = "Plots are private blocks of land rentable from the NPC Farmer located on the South East side of Varbosa. After speaking with him and paying at least a weeks worth of rent (10k), you can access your plot by stepping on the red carpet and you will be teleported to your plot. Only characters from your account can access the plot and you can only rent 1 plot per account. Making extra accounts for extra plots is against the rules and will result in harsh penalties.\n\nOnce at your plot you can “use” seeds gained from Farming on the ground to start growing a new personal plant to be harvested. An animation will show on successful planting of a seed and they will take time to grow into a harvestable plant.\n\nThese personal plants are the same as their wild counterparts, they will give Farming skill, fruits and seeds, only they will not respawn once broken. You will have to plant another seed in its place if you want another plant to grow.\n\nTier 1: Cloud Bell (Farming level required: 10)\nTier 2: Banora (Farming level required: 15)\nTier 3: Nightlock (Farming level required: 20)\nTier 4: Niphredil (Farming level required: 40)\nTier 5: Groomsblood (Farming level required: 60)\nTier 6: Thorian (Farming level required: 80)", img = "imgs/profesion/f2"},
         {name = "- Plants", text = "1. Cloud Bell. Req Herbing lvl 10. \n2. Banora. Req Farming lvl 15\n3. Nightlock. Req Farming lvl 20\n4 Niphredil. Req Farming lvl 40\n5 Groomsblood. Req Farming lvl 60\n6 Thorian. Req Farming lvl 80", img = "imgs/profesion/Pl1"},
		 {name = "- Fruits", text = "1. Cloud Bell Fruit, \n2. Banora Fruit, \n3. Nightlock Fruit,\n4. Niphredil Fruit, \n5. Groomsblood Fruit, \n6. Thorian Fruit.", img = "imgs/profesion/Pl2"},
		 {name = "- Seeds", text = "1. Cloud Bell Seed, \n2. Banora Seed, \n3. Nightlock Seed,\n4. Niphredil Seed, \n5. Groomsblood Seed, \n6. Thorian Seed.", img = "imgs/profesion/Pl3"},
		{name = "04. Alchemy", text = "Alchemy is the skill used to create potions that boost your stats. You can view your current alchemy skill buy using the command !crafting\n\nTo make a potion you will needs fruits gained from Farming to determine the strength and one of creature products from the table below to determine what skill is increased.\n\nWhen you have your ingredients head to the South East of Verbose and speak to NPC Tarak to buy special vials. Use the empty vial on the cauldron with the ingredients you want to use in your backpack. Select which potion you want to make from the menu that pops up (in case you have more than 1 set of ingredients). The ingredients will be removed and replaced with the appropriate potion.\n\nTier 1: Cloud Bell 5% increase (Alchemy level: 10)\nTier 2: Banora [Strong] 10% increase (Alchemy level: 15)\nTier 3: Nightlock [Great] 15% increase (Alchemy level: 30)\nTier 4: Niphredil [Ultimate] 20% increase (Alchemy level: 45)\nTier 5: Groomsblood [Supreme] 25% increase (Alchemy level: 60)\nTier 6: Thorian [Lavish] 30% increase (Alchemy level: 80)\n\n\n- Infused (magic level): 3x Elvish Talisman / 5x Dragon's Tail / 15x Spider Silks / 20x Ogre Ear Studs / 40x Golden Lotus Broochs / 60x Book Pages.\n\n- Sharpened (sword skill): 3x Orc teeths / 5x Cave Turnips / 15x Blue Crystal Splinters / 20x Hellhound Slobbers / 40x Orbs / 60x Vexclaw Talons.\n\n- Balanced (axe skill): 3x Skull Belts / 5x Cultish Robes / 15x Brown Crystal Splinters / 20x Blazing Bones / 40x Hellflayer Horns / 60x Inkwells.\n\n- Weighted (club skill): 3x Orc Leathers / 5x Cyclops toes / 15x Red Crystal Fragments / 20x Demonic Essences / 40x Soul Orbs / 60x Piece of Dead Brains.\n\n- Precise (distance skill): 3x Minotaur Leathers / 5x Hellspawn Tails / 15x Hydra Heads / 20x Frazzle Tongues / 40x Peacock Feather Fans / 60x Silken Bookmarks.\n\n- Reinforced (shielding skill): 3x Green Dragon Leathers / 5x Green Dragon Scales / 15x Red Dragon Leathers / 20x Red Dragon Scales / 40x Frazzle Skins / 60x Fiery Hearts.", img = "imgs/profesion/a1"},  
		 {name = "- Crafting a Potion", text = "You use a flask, that can be brought from Tarak and use it on a Cauldron to make a Potion", img = "imgs/profesion/b1"},
		 {name = "- Tiers", text = "Here you'll have the option to make a potion if you have the req lvl.\nskill required to craft it.\nInfused: 10\nStrong: 15\nGreat: 30\nUltimate: 45\nSupreme: 60\nLavish: 80", img = "imgs/profesion/b2"},
		 {name = "- Potions", text = "Here is what the potions look like when crafted.\n1: Infused\n2: Strong\n3: Great\n4: Ultimate\n5: Supreme\n6: Lavish", img = "imgs/profesion/b3"},
		{name = "05. Enchanting", text = "Enchanting items applies different stat modifiers to any equipable item that doesn’t expire, have charges or is a container. Items can be enchanted with different types of enchant gems or come enchanted as loot from any creature that drops loot. Each time you use an enchant gem you gain experiance and can increase you enchanting level.\n\nThere are 6 different types of enchant gems:\n- Uncommon (1 modifier)\n- Rare (2 modifiers)\n- Epic (3 modifiers)\n- Legendary (4 modifiers)\n- Artifact (5 modifiers)\n- Random (1-5 modifiers)\n\nYou can obtain different enchant gems by killing Elite Monsters, Bosses, Disenchanting items or by completing Tasks. You can also purchase random enchant gems from the NPC Luna, she is located in the training area.\n\nStat Modifiers can increase stats between 1-10% except for Attack, Defence and Armor, which are flat value increases. Stat modifiers are randomly selected from the available modifiers allowed for the items slot type and you may have multiple stat modifier effect the same stat. In this case they are additive as well as with other items with the same stat modifier. Eg an item with the modifiers [magic level +5%] [magic level +3%] is the same as an item with the single modifier [magic level +8%]\n\nIncreasing your enchanting level increases the minium %enchant on an item up to a max of 5%. The following table reflects the bonus based on enchanting level. For example if you had 20 enchanting you would not roll below 2% on any gem you use.\n\n Enchanting perks:\n\nLevel 20: 2% minimum roll\nLevel 40: 3% minimum roll\nLevel 60: 4% minimum roll\nLevel 80: 5% minimum roll\n\nAn Enchant Copy Scroll take the stats from 1 item and place it onto a scroll. That scroll can be sold or used again on another item to re-apply the same stats that were coppied. Copy scrolls are extreamly rare and can only be obtained from world boss, raid boss and elite drops. Their are other means to obtain these scrolls but they will remain a secret.\n\nFor more information check Nutopia wiki.", img = "imgs/profesion/e1"},  
        {name = "06. Disenchanting", text = "Disenchanting is a skill on Nutopia that allows you to break exisiting enchanted items down back into their gem form. You can take for example an epic item, place it in the disenchanting chest and have a 50% base chance to receive an epic enchant gem back in its place. This base chance increases by 0.2% fo each level so at disenchanting 80 the player has a 66% chance to break each item down to its gem form.\n\nTo disenchant an item head to the disenchanting rooms below varbosa DP. Once in a room place all items inside the chest you wish to dis-enchant and hit the lever. This will instantly convert all items inside the chest back into their gem form based on a % chance. Certain disenchanting levels are required to break down an enchanted item, the following table reflects this:\n\nLevel 0: Uncommon\nLevel 20: Rare\nLevel 40: Epic\nLevel 60: Legendary\nLevel 80: Artifact", img = "imgs/profesion/d1"},  
},	
    {
        {name = "01. Outfits-Addons", text = "All around the map, deep in spawns and in raids, are world bosses. These bosses hold the best loot available.\n\nKilling a boss monster will give an achievement to each party member in the killers share range. It will also spawn a portal that will take you to the outfit reward room where you can open a chest and claim an outfit. \n\nEach boss has its own unique outfit reward. \n\nIf you need more information about bosses you can find them here.\nhttps://nutopia.fandom.com/wiki/Bosses", img = "imgs/basic/a"},
        {name = "02. Mounts", text = "Mounts are obtained by trading various items and money with NPC Jeff who is North West of Varbosa depot.\n\nYou can check the complete list on Nutopia Wiki!", img = "imgs/basic/m1"}, 
    },
    {
        {name = "01. Raids", text = "Raids are the endgame challenges of the server. There are 4 to be found in the world, each with increasing difficulty. They offer the toughest challenges and best rewards the server has to offer. Party up and face these challenges!\n\nRaid 1: The demonic Inquisition\n- 8 Bosses\n- Recommended Level 200\n\nRaid 2: The World Rift\n- 5 Bosses\n- Recommended level 400\n\nRaid 3: The Black Dock\n- 7 Bosses\n- Recommended level 600\n\nRaid 4: The Elemental Plains\n- ??? Bosses\n- Recommended level 800", img = "imgs/basic/raids"},
    },		

    {
        {name = "The most important rule",      text = "If the admins of the server have to spend more time on you then the server itself because your trying to flirt around the semantics of the rules you will just be banned. \n\nWe don't have time to deal with people going out of their way to be difficult. You can dispute decisions provided its fair and reasonable but if your being a pest then prepare to pay the price.", img = "imgs/rules/rules"},
        {name = "01. Bugs and exploits", text = "Bug abuse and exploiting is not on. If you notice a bug you are to report it and not use it for any personal gain or malicious activities.", img = "imgs/rules/rules"},
        {name = "02. IRL threats",         text = "Irl threats, doxing or racism in discord is not on. I have no issue with people talking shit and insulting each other as long as those lines are not crossed.", img = "imgs/rules/rules"},
        {name = "03. Griefing",             text = "Greifing in excess eg: Going out of your way to ruin someone’s experience repeatably or continuously. There will always be some forms of griefing between players and there has to be some level of acceptance of this stuff happening on the server, its tibia after all. \n\nWhat constitutes greifing: \n\n- Following a player/players around for an extended period of time between spawns trying to block them with mwalls, steal mobs, luring and trying to get them killed. This includes following people to other spawns & being an excessive pest. \n\n-Dragging or blocking a lootable cropse so that the people who rightfully got the kill cant obtain there loot, especially if your not the loot owner. \n\nWhat doesn’t constitute greifing: \n\nBeing verbally abused (so long as its not irl, doxing, racist etc) - Competing over a spawn provided that the competition only remains at the spawn and doesn’t involve into point 1 in “what constitutes greifing”. - If your spawn is “crashed” by another player you are entitled to try get them killed if they have pvp off or kill them if they have pvp on provided the conflict ends at that spawn and doesn’t translate into other areas. Don’t follow between spawns. If the spawn is clearly big enough for multiple people then let them hunt and don't grief. \n\nIt is up to the decision of the Server Manager as what constitutes greifing and what doesn’t.", img = "imgs/rules/rules"},
        {name = "04. Botting/Macroing",          text = "Cave boting either at or away from the PC is strictly against the rules \n- AFK macroing is strictly against the rules \n- Auto heal macros, auto targeting macros and things of this nature are against the rules \n- The use of macros is hard to police. Sometimes macros are used for minor quality of live improvements. You can use some macros provided they aren't automating your char while AFK. \n\nBotting/automated macros are against the server rules. If you are caught cave botting you progress strait to 24 hour ban.", img = "imgs/rules/rules"},
        {name = "05. Admin Abuse",     text = "Abusing admins, being cunts to them or going out of your way to make their life hard is against the rules.", img = "imgs/rules/rules"},
        {name = "06. MC",   text = "4 chars per IP, you cant use MC's to level chars through tasks or other means simultaneously. This rule is in place so brothers on the same connection or friends can still play.", img = "imgs/rules/rules"},
        {name = "07. Complains",    text = "Dont complain about dying at bosses you take the risk going their. Its PvP enforced. Having 'spy' chars set up at multiple bosses on numerous accounts is against the rules.", img = "imgs/rules/rules"},
        {name = "08. Pots",     text = "You are strictly only allowed to have 1 farming plot per person due to how the system works. \n\nIf you try to obtain more then 1 plot person person you will receive 1 warning with the second plot being deleted. \n\nIf you do it again you will be banned, we don't have time to be fucking around with this stuff so a 0 tolerance policy will be used after the first warning.", img = "imgs/rules/rules"},
        {name = "General Disciplinary Actions",       text = "First Official Warning - 24 hour IP Ban - 1 Week IP Ban - Permanent Ban", img = "imgs/rules/rules"},
    },	 
    {
        {name = "FAQ's", text = "Can I rebind my hotkeys in the client?\nYes. All keys can be rebound, select “add” under kotkeys to customise keys.\n\nMy magic level is capped at 255?\nThis is a client limitation and only visual. Use the command !mlvl to see what your actual magic level is.\n\nWhy would I use softboots if I can’t enchant them?\nSoftboots give 10x hp and mana regeneration compared to real tibia to make up for this.\n\nAs a knight, am I really going to spend my whole time chugging mana potions?\nKnights and Paladins can use great mana potions in Nutopia\n\nAs a paladin, am I going to have to cap out on arrows every hunt?\n- Normal arrows, bolts and burst arrows are infinite\n- Diamond arrows have a 30% chance to break each hit\n- All other ammunition has a 10% chance to break each hit\n\nAs a mage, my wand rod feels pretty useless but I don’t want to carry a sword either?\nWand and rods do 3x damage compared to real tibia\n\nCan I use a bot?\nNO! This is bot free server and you will be deleted without warning!\n\nWhere can i buy random enchant gems?\nYou can find these from luna in the trainers\n\nHow does the enchant copy scroll work?\nThe way it works is it copy off the enchant from said item and has to be put back on the same item item for example:\n- Armor -> Armor\n- Legs -> Legs\n- 1hand -> 1hand\n- 2hand -> 2hand", img = "imgs/rules/faq"},
    },
}